name: Deploy to Vercel

on:
  push:
    branches:
      - main # Thay đổi tên nhánh nếu cần
  pull_request:
    branches:
      - main # Tự động triển khai khi có pull request vào nhánh chính

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Thay đổi phiên bản Node.js nếu cần

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Thêm token Vercel vào Secrets
          vercel-args: "--prod" # Triển khai lên môi trường sản xuất
          working-directory: . # Đường dẫn đến thư mục chứa dự án (nếu không phải là gốc)

        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # Thêm ID tổ chức vào Secrets
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Thêm ID dự án vào Secrets
